In [ ]:
# import the required lib

import numpy as np
import pandas as pd

In [ ]:
# read the data

df = pd.read_csv('/content/emp_promotion.csv')

In [ ]:
# Visualize the dataset

df

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,3030,Technology,region_14,Bachelor's,m,sourcing,1,48,3.0,17,0,0,78,0
54804,74592,Operations,region_27,Master's & above,f,other,1,37,2.0,6,0,0,56,0
54805,13918,Analytics,region_1,Bachelor's,m,other,1,27,5.0,3,1,0,79,0
54806,13614,Sales & Marketing,region_9,NaN,m,sourcing,1,29,1.0,2,0,0,45,0
54807,51526,HR,region_22,Bachelor's,m,other,1,27,1.0,5,0,0,49,0

In [ ]:
df.head(8)

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0
5,58896,Analytics,region_2,Bachelor's,m,sourcing,2,31,3.0,7,0,0,85,0
6,20379,Operations,region_20,Bachelor's,f,other,1,31,3.0,5,0,0,59,0
7,16290,Operations,region_34,Master's & above,m,sourcing,1,33,3.0,6,0,0,63,0

In [ ]:
df.tail()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
54803,3030,Technology,region_14,Bachelor's,m,sourcing,1,48,3.0,17,0,0,78,0
54804,74592,Operations,region_27,Master's & above,f,other,1,37,2.0,6,0,0,56,0
54805,13918,Analytics,region_1,Bachelor's,m,other,1,27,5.0,3,1,0,79,0
54806,13614,Sales & Marketing,region_9,NaN,m,sourcing,1,29,1.0,2,0,0,45,0
54807,51526,HR,region_22,Bachelor's,m,other,1,27,1.0,5,0,0,49,0

In [ ]:
# Find the dtype

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           54808 non-null  int64
 1   department            54808 non-null  object
 2   region                54808 non-null  object
 3   education             52399 non-null  object
 4   gender                54808 non-null  object
 5   recruitment_channel   54808 non-null  object
 6   no_of_trainings       54808 non-null  int64
 7   age                   54808 non-null  int64
 8   previous_year_rating  50684 non-null  float64
 9   length_of_service     54808 non-null  int64
 10  KPIs_met >80%         54808 non-null  int64
 11  awards_won?           54808 non-null  int64
 12  avg_training_score    54808 non-null  int64
 13  is_promoted           54808 non-null  int64
dtypes: float64(1), int64(8), object(5)
memory usage: 5.9+ MB

In [ ]:
# descriptive stat

df.describe(include='all')

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
count,54808.000000,54808,54808,52399,54808,54808,54808.000000,54808.000000,50684.000000,54808.000000,54808.000000,54808.000000,54808.000000,54808.000000
unique,NaN,9,34,3,2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Sales & Marketing,region_2,Bachelor's,m,other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,16840,12343,36669,38496,30446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,39195.830627,NaN,NaN,NaN,NaN,NaN,1.253011,34.803915,3.329256,5.865512,0.351974,0.023172,63.386750,0.085170
std,22586.581449,NaN,NaN,NaN,NaN,NaN,0.609264,7.660169,1.259993,4.265094,0.477590,0.150450,13.371559,0.279137
min,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000,20.000000,1.000000,1.000000,0.000000,0.000000,39.000000,0.000000
25%,19669.750000,NaN,NaN,NaN,NaN,NaN,1.000000,29.000000,3.000000,3.000000,0.000000,0.000000,51.000000,0.000000
50%,39225.500000,NaN,NaN,NaN,NaN,NaN,1.000000,33.000000,3.000000,5.000000,0.000000,0.000000,60.000000,0.000000
75%,58730.500000,NaN,NaN,NaN,NaN,NaN,1.000000,39.000000,4.000000,7.000000,1.000000,0.000000,76.000000,0.000000
max,78298.000000,NaN,NaN,NaN,NaN,NaN,10.000000,60.000000,5.000000,37.000000,1.000000,1.000000,99.000000,1.000000

In [ ]:
# Finding Null values

df.isnull()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,False,False,False,False,False,False,False,False,False,False,False,False,False,False
54804,False,False,False,False,False,False,False,False,False,False,False,False,False,False
54805,False,False,False,False,False,False,False,False,False,False,False,False,False,False
54806,False,False,False,True,False,False,False,False,False,False,False,False,False,False
54807,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Finding Null values

df.isnull().any()

employee_id             False
department              False
region                  False
education                True
gender                  False
recruitment_channel     False
no_of_trainings         False
age                     False
previous_year_rating     True
length_of_service       False
KPIs_met >80%           False
awards_won?             False
avg_training_score      False
is_promoted             False
dtype: bool

In [ ]:
# Finding Null values

df.isnull().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [ ]:
# Handling the null values

"""
2 ways to handle the null values
    1) removing the null value --- (dropna()) [10000 obs, 10 null values] or [10000 obs, 6000 null values]
    2) Replacing the null values --- (fillna()) [10000 obs, 1000 null values]
"""

'\n2 ways to handle the null values\n    1) removing the null value --- (dropna()) [10000 obs, 10 null values] or [10000 obs, 6000 null values]\n    2) Replacing the null values --- (fillna()) [10000 obs, 1000 null values]\n'

In [ ]:
df['education'].mode()[0]

"Bachelor's"

In [ ]:
df['previous_year_rating'].mean()

np.float64(3.329255780917055)

In [ ]:
df['education'] = df['education'].fillna(df['education'].mode()[0])

NameError: name 'df' is not defined

In [ ]:
df['previous_year_rating'] = df['previous_year_rating'].fillna(df['previous_year_rating'].mean())

In [ ]:
df.isnull().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [ ]:
df.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0

In [ ]:
# Selecting a specific data types
#1) Categorical Info** :  Holds important labels like city names, department names, grades etc.
#2) Feature Engineering** : Can be converted into numeric values using encoding techniques for modeling.
#3) Grouping/Aggregation** : Often used for `groupby()` operations.
#4) **Data Cleaning Target** : Usually requires cleaning (e.g., trimming, replacing text, fixing typos).
#5) **Needs Conversion** : Cannot be used directly in ML models; must be encoded to numeric first.

df.select_dtypes(exclude='object')

,employee_id,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,1,35,5.0,8,1,0,49,0
1,65141,1,30,5.0,4,0,0,60,0
2,7513,1,34,3.0,7,0,0,50,0
3,2542,2,39,1.0,10,0,0,50,0
4,48945,1,45,3.0,2,0,0,73,0
...,...,...,...,...,...,...,...,...,...
54803,3030,1,48,3.0,17,0,0,78,0
54804,74592,1,37,2.0,6,0,0,56,0
54805,13918,1,27,5.0,3,1,0,79,0
54806,13614,1,29,1.0,2,0,0,45,0
54807,51526,1,27,1.0,5,0,0,49,0

In [ ]:
# Selecting a specific data types

df.select_dtypes(include='object')

,department,region,education,gender,recruitment_channel
0,Sales & Marketing,region_7,Master's & above,f,sourcing
1,Operations,region_22,Bachelor's,m,other
2,Sales & Marketing,region_19,Bachelor's,m,sourcing
3,Sales & Marketing,region_23,Bachelor's,m,other
4,Technology,region_26,Bachelor's,m,other
...,...,...,...,...,...
54803,Technology,region_14,Bachelor's,m,sourcing
54804,Operations,region_27,Master's & above,f,other
54805,Analytics,region_1,Bachelor's,m,other
54806,Sales & Marketing,region_9,Bachelor's,m,sourcing
54807,HR,region_22,Bachelor's,m,other

In [ ]:
df['department'].unique()

array(['Sales & Marketing', 'Operations', 'Technology', 'Analytics',
       'R&D', 'Procurement', 'Finance', 'HR', 'Legal'], dtype=object)

In [ ]:
df['department'].value_counts()

department
Sales & Marketing    16840
Operations           11348
Technology            7138
Procurement           7138
Analytics             5352
Finance               2536
HR                    2418
Legal                 1039
R&D                    999
Name: count, dtype: int64

In [ ]:
df['recruitment_channel'].value_counts()

recruitment_channel
other       30446
sourcing    23220
referred     1142
Name: count, dtype: int64

In [ ]:
df.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0

In [ ]:
# Removing the unwanted columns

df = df.drop('employee_id',axis=1)
df.head()

,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0

In [ ]:
# Encoding - 1)One Hot encoding, 2)Label encoding & 3)Manual encoding

In [ ]:
# One hot encoding

pd.get_dummies(df['department'])

,Analytics,Finance,HR,Legal,Operations,Procurement,R&D,Sales & Marketing,Technology
0,False,False,False,False,False,False,False,True,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...
54803,False,False,False,False,False,False,False,False,True
54804,False,False,False,False,True,False,False,False,False
54805,True,False,False,False,False,False,False,False,False
54806,False,False,False,False,False,False,False,True,False
54807,False,False,True,False,False,False,False,False,False

In [ ]:
# Label encoding

# Apple, Shoes, Aeroplane
#   1      2       0

from sklearn.preprocessing import LabelEncoder

In [ ]:
le1 = LabelEncoder()

In [ ]:
df['department'] = le1.fit_transform(df['department'])

In [ ]:
df.head()

,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,7,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,4,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,7,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,8,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0

In [ ]:
le1.inverse_transform([4])

array(['Operations'], dtype=object)

In [ ]:
# Step 1 Initialize

le2 = LabelEncoder()

In [ ]:
# Step 2 Transform the values

df['region'] = le2.fit_transform(df['region'])

In [ ]:
df.head()

,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,7,31,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,4,14,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7,10,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,7,15,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,8,18,Bachelor's,m,other,1,45,3.0,2,0,0,73,0

In [ ]:
le3 = LabelEncoder()

In [ ]:
df['education'] = le3.fit_transform(df['education'])

df.head()

,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,7,31,2,f,sourcing,1,35,5.0,8,1,0,49,0
1,4,14,0,m,other,1,30,5.0,4,0,0,60,0
2,7,10,0,m,sourcing,1,34,3.0,7,0,0,50,0
3,7,15,0,m,other,2,39,1.0,10,0,0,50,0
4,8,18,0,m,other,1,45,3.0,2,0,0,73,0

In [ ]:
# Manual encoding

In [ ]:
df['gender'].unique()

array(['f', 'm'], dtype=object)

In [ ]:
df['gender'] = df['gender'].replace({'f':0,'m':1})
df.head()

/tmp/ipython-input-39-3729952743.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['gender'] = df['gender'].replace({'f':0,'m':1})

,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,7,31,2,0,sourcing,1,35,5.0,8,1,0,49,0
1,4,14,0,1,other,1,30,5.0,4,0,0,60,0
2,7,10,0,1,sourcing,1,34,3.0,7,0,0,50,0
3,7,15,0,1,other,2,39,1.0,10,0,0,50,0
4,8,18,0,1,other,1,45,3.0,2,0,0,73,0

In [ ]:
df['recruitment_channel'].unique()

array(['sourcing', 'other', 'referred'], dtype=object)

In [ ]:
df['recruitment_channel'] = df['recruitment_channel'].replace({'sourcing':0,'other':1,'referred':2})
df.head()

/tmp/ipython-input-41-4200040549.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['recruitment_channel'] = df['recruitment_channel'].replace({'sourcing':0,'other':1,'referred':2})

,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,7,31,2,0,0,1,35,5.0,8,1,0,49,0
1,4,14,0,1,1,1,30,5.0,4,0,0,60,0
2,7,10,0,1,0,1,34,3.0,7,0,0,50,0
3,7,15,0,1,1,2,39,1.0,10,0,0,50,0
4,8,18,0,1,1,1,45,3.0,2,0,0,73,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   department            54808 non-null  int64
 1   region                54808 non-null  int64
 2   education             54808 non-null  int64
 3   gender                54808 non-null  int64
 4   recruitment_channel   54808 non-null  int64
 5   no_of_trainings       54808 non-null  int64
 6   age                   54808 non-null  int64
 7   previous_year_rating  54808 non-null  float64
 8   length_of_service     54808 non-null  int64
 9   KPIs_met >80%         54808 non-null  int64
 10  awards_won?           54808 non-null  int64
 11  avg_training_score    54808 non-null  int64
 12  is_promoted           54808 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 5.4 MB

In [ ]:
# Split the dependent and independent data

x = df.drop('is_promoted',axis=1)
y = df['is_promoted']

In [ ]:
# Split the data for training and testing

from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=12)

In [ ]:
xtrain.shape, xtest.shape

((38365, 12), (16443, 12))

In [ ]:
xtrain.head()

,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score
29677,5,18,1,0,1,1,23,3.329256,1,1,0,66
52628,4,6,0,1,1,1,42,5.000000,3,0,0,63
4041,3,11,0,1,0,1,34,5.000000,4,1,0,59
26140,7,12,0,1,1,1,38,5.000000,7,0,0,45
5671,7,14,2,0,1,1,40,3.000000,3,0,0,49

In [ ]:
# Scaling the values 1) Standard scaler 2) MinMax scaler

from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
n = MinMaxScaler()

In [ ]:
xtrain_scaled = n.fit_transform(xtrain)

In [ ]:
xtrain_scaled

array([[0.625     , 0.54545455, 0.5       , ..., 1.        , 0.        ,
        0.45      ],
       [0.5       , 0.18181818, 0.        , ..., 0.        , 0.        ,
        0.4       ],
       [0.375     , 0.33333333, 0.        , ..., 1.        , 0.        ,
        0.33333333],
       ...,
       [0.875     , 0.72727273, 0.        , ..., 1.        , 0.        ,
        0.15      ],
       [0.875     , 0.45454545, 1.        , ..., 0.        , 0.        ,
        0.18333333],
       [0.875     , 0.39393939, 0.        , ..., 0.        , 0.        ,
        0.21666667]])

In [ ]:
s = StandardScaler()

In [ ]:
xtrainScaled = s.fit_transform(xtrain)

In [ ]:
xtrainScaled

array([[ 0.01001704,  0.29807729,  0.49361104, ...,  1.35289353,
        -0.15437334,  0.19941564],
       [-0.38905238, -1.07274417, -0.63000279, ..., -0.73915646,
        -0.15437334, -0.02492184],
       [-0.78812181, -0.50156856, -0.63000279, ...,  1.35289353,
        -0.15437334, -0.32403847],
       ...,
       [ 0.80815589,  0.98348802, -0.63000279, ...,  1.35289353,
        -0.15437334, -1.14660922],
       [ 0.80815589, -0.04462807,  1.61722486, ..., -0.73915646,
        -0.15437334, -0.99705091],
       [ 0.80815589, -0.27309832, -0.63000279, ..., -0.73915646,
        -0.15437334, -0.84749259]])

In [ ]:
xtestScaled = s.transform(xtest)

In [ ]:
xtestScaled

array([[-0.38905238,  1.897369  , -0.63000279, ..., -0.73915646,
        -0.15437334, -0.24925932],
       [ 0.80815589, -0.95850905, -0.63000279, ...,  1.35289353,
        -0.15437334, -0.69793427],
       [-1.98533008,  1.897369  , -0.63000279, ..., -0.73915646,
        -0.15437334,  1.62021966],
       ...,
       [ 0.80815589,  1.44042851,  1.61722486, ...,  1.35289353,
         6.47780257, -0.99705091],
       [ 0.01001704, -0.50156856,  1.61722486, ..., -0.73915646,
        -0.15437334,  0.2741948 ],
       [ 0.80815589, -0.50156856,  1.61722486, ...,  1.35289353,
        -0.15437334, -0.84749259]])